application:
  environment: @cloud.profile@
  root-context: /wap/holiday
spring:
  application:
    name: holiday
  profiles:
    active: @cloud.profile@
  http:
    converters:
      preferred-json-mapper: gson
  flyway:
    schemas: [ holiday ]
    locations:
      - "classpath:META-INF/db/migration"
    default-schema: holiday
server:
  port: @application.port@
  servlet:
    context-path: @application.context-path@
